[build]
dockerfilePath = "Dockerfile.railway"

[deploy]
preDeployCommand = "venv/bin/python manage.py migrate"
healthcheckPath = "/admin/login/"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
